---
sudo: false
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0
  - 2.2.2
addons:
  code_climate:
    repo_token: 38686058eed480dd0fcf8bce9015733e0bae88e44e30f4a1ac63df8aec2f86d8
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
script:
  # Test for knapsack gem
  - bin/print_header.sh "Run specs for Knapsack gem"
  - bundle exec rspec spec


  - bin/print_header.sh "------------------------------------------------------"


  # Tests for example rspec test suite
  - bin/print_header.sh "Generate knapsack report"
  - KNAPSACK_GENERATE_REPORT=true bundle exec rspec --default-path spec_examples --tag focus

  - bin/print_header.sh "Run specs with enabled time offset warning"
  - bundle exec rspec --default-path spec_examples

  - bin/print_header.sh "Run rake task for the first CI node"
  - CI_NODE_TOTAL=2 CI_NODE_INDEX=0 KNAPSACK_TEST_FILE_PATTERN="spec_examples/**/*_spec.rb" bundle exec rake knapsack:rspec
  - bin/print_header.sh "Run rake task for the second CI node"
  - CI_NODE_TOTAL=2 CI_NODE_INDEX=1 KNAPSACK_TEST_FILE_PATTERN="spec_examples/**/*_spec.rb" bundle exec rake knapsack:rspec

  - bin/print_header.sh "Check passing arguments to rspec. Run only specs with custom_focus tag"
  - KNAPSACK_TEST_FILE_PATTERN="spec_examples/**/*_spec.rb" bundle exec rake "knapsack:rspec[--tag custom_focus]"
  - KNAPSACK_TEST_FILE_PATTERN="spec_examples/**/*_spec.rb" bin/knapsack rspec "--tag custom_focus --profile"

  - bin/print_header.sh "Run specs with custom knapsack logger"
  - CUSTOM_LOGGER=true KNAPSACK_TEST_FILE_PATTERN="spec_examples/**/*_spec.rb" bundle exec rake knapsack:rspec

  - bin/print_header.sh "Run specs for custom knapsack report path"
  - cp knapsack_rspec_report.json knapsack_custom_rspec_report.json
  - KNAPSACK_REPORT_PATH="knapsack_custom_rspec_report.json" KNAPSACK_TEST_FILE_PATTERN="spec_examples/**/*_spec.rb" bundle exec rake knapsack:rspec

  - bin/print_header.sh "Run specs when spec file was removed and still exists in knapsack report json"
  - rm spec_examples/fast/1_spec.rb
  - KNAPSACK_TEST_FILE_PATTERN="spec_examples/**/*_spec.rb" bundle exec rake knapsack:rspec


  - bin/print_header.sh "------------------------------------------------------"


  # Tests for example minitest test suite
  - bin/print_header.sh "Generate knapsack report"
  - KNAPSACK_GENERATE_REPORT=true bundle exec rake test

  - bin/print_header.sh "Run tests with enabled time offset warning"
  - bundle exec rake test

  - bin/print_header.sh "Run rake task for the first CI node"
  - CI_NODE_TOTAL=2 CI_NODE_INDEX=0 KNAPSACK_TEST_FILE_PATTERN="test_examples/**/*_test.rb" bundle exec rake knapsack:minitest
  - bin/print_header.sh "Run rake task for the second CI node"
  - CI_NODE_TOTAL=2 CI_NODE_INDEX=1 KNAPSACK_TEST_FILE_PATTERN="test_examples/**/*_test.rb" bundle exec rake knapsack:minitest

  - bin/print_header.sh "Check passing arguments to minitest. Run verbose tests"
  - KNAPSACK_TEST_FILE_PATTERN="test_examples/**/*_test.rb" bundle exec rake "knapsack:minitest[--verbose]"
  - KNAPSACK_TEST_FILE_PATTERN="test_examples/**/*_test.rb" bin/knapsack minitest "--verbose --pride"

  - bin/print_header.sh "Run tests with custom knapsack logger"
  - CUSTOM_LOGGER=true KNAPSACK_TEST_FILE_PATTERN="test_examples/**/*_test.rb" bundle exec rake knapsack:minitest

  - bin/print_header.sh "Run tests for custom knapsack report path"
  - cp knapsack_minitest_report.json knapsack_custom_minitest_report.json
  - KNAPSACK_REPORT_PATH="knapsack_custom_minitest_report.json" KNAPSACK_TEST_FILE_PATTERN="test_examples/**/*_test.rb" bundle exec rake knapsack:minitest

  - bin/print_header.sh "Run tests when test file was removed and still exists in knapsack report json"
  - rm test_examples/fast/unit_test.rb
  - KNAPSACK_TEST_FILE_PATTERN="test_examples/**/*_test.rb" bundle exec rake knapsack:minitest
notifications:
  email: false
